# kn_sn_training.yaml

## Where the samples will be written
save_data: run/example
## Where the vocab(s) will be written
src_vocab: run/example.vocab.src
tgt_vocab: run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: train/tokenized.tr.kn
        path_tgt: train/tokenized.tr.sn
    valid:
        path_src: dev/tokenized.dev.kn
        path_tgt: dev/tokenized.dev.sn

# Vocabulary files that were just created
src_vocab: run/example.vocab.src
tgt_vocab: run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: run/model
save_checkpoint_steps: 1000
train_steps: 10000
valid_steps: 500
learning_rate: 2
